#!/usr/bin/env sh

# shellcheck disable=SC1091
hc() {
	herbstclient "$@"
}

hc emit_hook reload
xsetroot -solid '#333333'

source ~/.config/herbstluftwm/keys
source ~/.config/herbstluftwm/rules
source ~/.config/herbstluftwm/theme
#-- if themeOVERRIDE exists source it after theme
OVERRIDE=~/.config/herbstluftwm/themeOVERRIDE
[ -f $OVERRIDE ] && source $OVERRIDE

hc detect_monitors
for monitor in $(hc list_monitors | cut -d':' -f1); do
	hc pad "$monitor" 25
done

hc focus_monitor 2
hc use 7
hc focus_monitor 1
hc use 4
hc focus_monitor 0
hc use 1

#-----------#
# Autostart #
#-----------#
source "$HOME"/.fehbg
xmodmap ~/.config/xmodmap & # Key remaps
picom & # Compostior
polybar_launcher & # Info panels
startsinks & # Audio Sinks
qpwgraph & # Pipewire Patchboard
steam & # Games
xfce4-power-manager &

# NOTE: Avoiding duplicate processes if reloading configs
# Check if not running via pgrap '-c for count' '-a full name to use with grep' && launch 
[[ $(pgrep -c "unclutter") == 0 ]] && unclutter --timeout 15 --ignore-scrolling &
[[ $(pgrep -a "python3" | grep "/usr/bin/jack_mixer" | wc -l) == 0 ]] && jack_mixer -c ~/.config/jack_mixer/master.xml &
#[[ $(pgrep -c "schildichat") == 0 ]] && schildichat-desktop &

