#!/usr/bin/env sh

hc() {
	herbstclient "$@"
}

hc emit_hook reload
xsetroot -solid '#003333'

source ~/.config/herbstluftwm/keybinds
source ~/.config/herbstluftwm/rules
source ~/.config/herbstluftwm/theme

hc detect_monitors
for monitor in $(hc list_monitors | cut -d':' -f1); do
	hc pad $monitor 25
done

#-----------#
# Autostart #
#-----------#
polybar_launcher &
dunst &

JACKMIXCHECK=$(pgrep -a "python3" | grep "/usr/bin/jack_mixer" | wc -l)
if [[ $JACKMIXCHECK == 0 ]]; then
	jack_mixer -c ~/.config/jack_mixer/master.xml &
	echo "System" > ~/.config/polybar/scripts/var
fi

discord &
#spotify-launcher &
#obs &
