#!/usr/bin/env sh
hc() {
		herbstclient "$@"
}

###--------------------###
###---   Settings   ---###
###--------------------###
hc keyunbind --all
hc mouseunbind --all

# if you have a super key you will be much happier with Mod set to Mod4
#MOD=Mod1		# Use Alt as the main modifier
MOD=Mod4   # Use the super key as the main modifier

###-------------------------###
###---   Mouse Buttons   ---###
###-------------------------###
hc mousebind $MOD-Button1 move
hc mousebind $MOD-Button2 zoom
hc mousebind $MOD-Button3 resize

###--------------------###
###---   Spawning   ---###
###--------------------###
hc keybind $MOD-Return spawn ${TERMINAL}
hc keybind $MOD-w spawn ${BROWSER:-firefox}
hc keybind $MOD-Shift-w spawn ${BROWSER} -private-window
#hc keybind $MOD-Control-w spawn ${BROWSER} --tor
hc keybind $MOD-c spawn rofi -show calc -no-show-match -no-sort
hc keybind $MOD-e spawn kitty --class kitty.float -e ranger
hc keybind $MOD-Shift-e spawn ${VISUALFILEMAN:-thunar}
hc keybind $MOD-r spawn rofi -show run
hc keybind $MOD-Home spawn feh --no-xinerama --bg-scale --randomize ~/Pictures/Wallpapers
hc keybind $MOD-s spawn ~/.config/rofi/scripts/switch_sinks.sh

###--------------------------###
###---   Screenshooting   ---###
###--------------------------###
hc keybind Print spawn zshot full
hc keybind Control-Print spawn zshot select
hc keybind Alt-Print spawn \
	scrot -ub -F ~/pictures/screenshots/Window_%s_'$w'x'$h'.png -e 'xclip -selection clipboard -t image/png -i $f'

hc keybind Shift-Print chain , \
	spawn scrot -M 0 -F ~/pictures/screenshots/Mon-0_%s_'$w'x'$h'.png , \
	spawn scrot -M 1 -F ~/pictures/screenshots/Mon-1_%s_'$w'x'$h'.png , \
	spawn scrot -M 2 -F ~/pictures/screenshots/Mon-2_%s_'$w'x'$h'.png

###-----------------###
###---   Split   ---###
###-----------------###
hc keybind $MOD-p chain ,\
	split left 0.3 ,\
	focus left
hc keybind $MOD-o chain ,\
	split right	0.7 ,\
	focus right
hc keybind $MOD-Shift-o chain , \
	split left 0.3 , \
	focus left
hc keybind $MOD-u chain , \
	split bottom 0.7 , \
	focus down
hc keybind $MOD-Shift-u chain , \
	split top 0.3 , \
	focus up

###-----------------###
###---   Focus   ---###
###-----------------###
hc keybind $MOD-Left 	focus left
hc keybind $MOD-Down 	focus down
hc keybind $MOD-Up 		focus up
hc keybind $MOD-Right focus right
hc keybind $MOD-h 		focus left
hc keybind $MOD-j 		focus down
hc keybind $MOD-k 		focus up
hc keybind $MOD-l 		focus right

hc keybind $MOD-BackSpace   cycle_monitor
hc keybind $MOD-Tab 				cycle +1
hc keybind $MOD-Shift-Tab   cycle_all +1
hc keybind $MOD-i jumpto urgent

hc keybind $MOD-bracketleft   use_index -1 --skip-visible
hc keybind $MOD-bracketright	use_index +1 --skip-visible
hc keybind $MOD-comma	focus_monitor +1
hc keybind $MOD-period focus_monitor -1

###--------------------###
###---   Movement   ---###
###--------------------###
hc keybind $MOD-Shift-h shift left
hc keybind $MOD-Shift-j shift down
hc keybind $MOD-Shift-k shift up
hc keybind $MOD-Shift-l shift right
hc keybind $MOD-Shift-bracketleft	move_index -1 --skip-visible
hc keybind $MOD-Shift-bracketright move_index +1 --skip-visible
hc keybind $MOD-Shift-comma	shift_to_monitor +1
hc keybind $MOD-Shift-period shift_to_monitor -1

###------------------###
###---   Resize   ---###
###------------------###
RESIZESTEP=0.02
hc keybind $MOD-Alt-h 		resize left +$RESIZESTEP
hc keybind $MOD-Alt-j 		resize down +$RESIZESTEP
hc keybind $MOD-Alt-k 		resize up +$RESIZESTEP
hc keybind $MOD-Alt-l 		resize right +$RESIZESTEP
hc keybind $MOD-Alt-Left 	resize left +$RESIZESTEP
hc keybind $MOD-Alt-Down 	resize down +$RESIZESTEP
hc keybind $MOD-Alt-Up 		resize up +$RESIZESTEP
hc keybind $MOD-Alt-Right resize right +$RESIZESTEP

###-------------------------###
###---   Display Modes   ---###
###-------------------------###
#hc keybind $MOD-r remove
hc keybind $MOD-f set_attr clients.focus.floating toggle
hc keybind $MOD-Shift-f fullscreen toggle
hc keybind $MOD-space cycle_layout +1
hc keybind $MOD-Shift-space cycle_layout -1
hc keybind $MOD-Control-space split explode

###--------------------------###
###---   Audio Controls   ---###
###--------------------------###
# My audio wheel is reversed
GETSINK=$(pamixer --list-sinks | grep "System" | awk '{ print $1 }')
hc keybind XF86AudioMute spawn pamixer --sink $GETSINK -t
hc keybind XF86AudioLowerVolume spawn pamixer --sink $GETSINK -i 5 # Raise Volume
hc keybind XF86AudioRaiseVolume spawn pamixer --sink $GETSINK -d 5 # Lower Volume
hc keybind XF86AudioPrev spawn playerctl previous -p spotify,%any
hc keybind XF86AudioPlay spawn playerctl play-pause -p spotify,%any
hc keybind XF86AudioNext spawn playerctl next -p spotify,%any

###------------------------------------###
###---   Reload/Restart/Kill/Exit   ---###
###------------------------------------###
hc keybind $MOD-q close_or_remove
hc keybind $MOD-Shift-q close
hc keybind $MOD-Control-Shift-q quit
hc keybind $MOD-Shift-r reload

###----------------###
###---   TAGS   ---###
###----------------###
hc attr settings.default_frame_layout vertical

TAGNAMES=( {1..10} )
TAGKEYS=( "1" "2" "3" "4" "5" "6" "7" "8" "9" "0" )

hc rename default "${TAGNAMES[0]}" || true
for i in "${!TAGNAMES[@]}" ; do
	hc add "${TAGNAMES[$i]}"
	KEY="${TAGKEYS[$i]}"
	if ! [ -z "$KEY" ] ; then
		hc keybind "$MOD-$KEY" chain , silent substitute M tags."$i".my_monitor focus_monitor M , use_index "$i"
#		hc keybind "$MOD-$KEY" use_index "$i"
		hc keybind "$MOD-Shift-$KEY" move_index "$i"
	fi
done
# Switch to previously viewd tag.
hc keybind "$MOD-Shift-grave" use_previous

###---------------------------###
###---   Add scratchpads   ---###
###---------------------------###
hc add sysadmin
hc add audio
hc keybind $MOD-grave spawn scratchpad sysadmin
hc keybind $MOD-Shift-XF86AudioMute spawn scratchpad audio

###--------------------###
###---   Tag Lock   ---###
###--------------------###
hc keybind $MOD-t chain \
	, new_attr string tags.focus.my_monitor \
	, substitute M monitors.focus.index set_attr tags.focus.my_monitor M \
	, try and \
		. compare monitors.focus.name != "" \
		. substitute M monitors.focus.name \
				set_attr tags.focus.my_monitor M
#
hc keybind $MOD-Shift-t \
	remove_attr tags.focus.my_monitor

###---------------###
###---   EOF   ---###
###---------------###
