#!/usr/bin/env sh
# shellcheck disable=SC1011,SC1090,SC1091,SC2016,SC2026,SC3009,SC3030,SC3046,SC3053,SC3054,SC3055
###--------------------###
###---  KEYBINDING  ---###
###---    ./keys    ---###
###--------------------###

###--------------------###
###---   Settings   ---###
###--------------------###
hc keyunbind --all
hc mouseunbind --all

#MOD=Mod1		# Use Alt as the main modifier
MOD=Mod4   # Use the super key as the main modifier

###-------------------------###
###---   Mouse Buttons   ---###
###-------------------------###
hc mousebind $MOD-Button1 move
hc mousebind $MOD-Button2 zoom
hc mousebind $MOD-Button3 resize

###--------------------###
###---   Spawning   ---###
###--------------------###
#hc keybind $MOD-Return spawn "${TERMINAL:-wezterm}"
hc keybind $MOD-Home spawn feh --no-xinerama --bg-scale --randomize ~/pictures/wallpapers
hc keybind $MOD-Return spawn "${TERMINAL:-wezterm}" start --class=Terminal
hc keybind $MOD-c spawn rofi -show calc -no-show-match -no-sort
hc keybind $MOD-e spawn "${VISUALFILEMAN:-thunar}"
hc keybind $MOD-r spawn rofi -show run
hc keybind $MOD-s spawn ~/.config/rofi/scripts/switch_sinks.sh
hc keybind $MOD-w spawn "${BROWSER:-firefox}"

hc keybind $MOD-Shift-w spawn "${BROWSER}" -private-window

###--------------------------###
###---   Screenshooting   ---###
###--------------------------###
hc keybind Release-Print spawn zshot full
hc keybind Release-Control-Print spawn zshot select
hc keybind Release-Alt-Print spawn \
	scrot -ub -F ~/pictures/screenshots/Window_%s_'$w'x'$h'.png -e 'xclip -selection clipboard -t image/png -i $f'

hc keybind Release-Shift-Print chain , \
	spawn scrot -M 0 -F ~/pictures/screenshots/Mon-0_%s_'$w'x'$h'.png , \
	spawn scrot -M 1 -F ~/pictures/screenshots/Mon-1_%s_'$w'x'$h'.png , \
	spawn scrot -M 2 -F ~/pictures/screenshots/Mon-2_%s_'$w'x'$h'.png

###-----------------###
###---   Focus   ---###
###-----------------###
hc keybind $MOD-h 		focus left
hc keybind $MOD-j 		focus down
hc keybind $MOD-k 		focus up
hc keybind $MOD-l 		focus right

hc keybind $MOD-BackSpace   cycle_monitor
hc keybind $MOD-Tab 				cycle +1
hc keybind $MOD-Shift-Tab   cycle_all +1
hc keybind $MOD-i jumpto urgent

hc keybind $MOD-bracketleft   use_index -1 --skip-visible
hc keybind $MOD-bracketright	use_index +1 --skip-visible
hc keybind $MOD-comma	focus_monitor +1
hc keybind $MOD-period focus_monitor -1

###--------------------###
###---   Movement   ---###
###--------------------###
hc keybind $MOD-Shift-h shift left
hc keybind $MOD-Shift-j shift down
hc keybind $MOD-Shift-k shift up
hc keybind $MOD-Shift-l shift right
hc keybind $MOD-Shift-bracketleft	move_index -1 --skip-visible
hc keybind $MOD-Shift-bracketright move_index +1 --skip-visible
hc keybind $MOD-Shift-comma	shift_to_monitor +1
hc keybind $MOD-Shift-period shift_to_monitor -1

###------------------###
###---   Resize   ---###
###------------------###
RESIZESTEP=0.02
hc keybind $MOD-Alt-h 		resize left +$RESIZESTEP
hc keybind $MOD-Alt-j 		resize down +$RESIZESTEP
hc keybind $MOD-Alt-k 		resize up +$RESIZESTEP
hc keybind $MOD-Alt-l 		resize right +$RESIZESTEP

###-------------------------###
###---   Display Modes   ---###
###-------------------------###
hc keybind $MOD-f set_attr clients.focus.floating toggle
hc keybind $MOD-Shift-f fullscreen toggle
hc keybind $MOD-space cycle_layout +1
hc keybind $MOD-Shift-space cycle_layout -1
	 ###-------------------###
	 ###---    Split    ---###
	 ###-------------------###
# Explode last window into a frame
hc keybind $MOD-Control-space split explode
# Open new vertical splits
# Right
hc keybind $MOD-o chain ,\
	split right	0.50 ,\
	focus right
# Left
hc keybind $MOD-Shift-o chain , \
	split right 0.75 , \
	focus right
# Under split horizontally
# 25% Bottom
hc keybind $MOD-u chain , \
	split bottom 0.75 , \
	focus down
# 50% Bottom
hc keybind $MOD-Shift-u chain , \
	split bottom 0.50 , \
	focus down

###--------------------------###
###---   Audio Controls   ---###
###--------------------------###
READSINK="~/.config/herbstluftwm/setsink"
if [ -f $READSINK ] && [ "$(cat $READSINK | wc -l)" -gt 0 ]; then
	SETSINK=$(cat $READSINK)
else
	SETSINK="@DEFAULT_SINK@"
fi

###---   Audio Mute Control   ---###
#hc keybind XF86AudioMute spawn pactl set-sink-mute "$SETSINK" toggle
#hc keybind $MOD-XF86AudioMute spawn ~/.config/herbstluftwm/scripts/rofi_getsink.sh
###---   My audio wheel is reversed   ---###
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume "$SETSINK" +5% # Raise Volume
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume "$SETSINK" -5% # Lower Volume
###--- Main Audio Controls   ---###
hc keybind XF86AudioPrev spawn playerctl previous -p sayonara,%any
hc keybind XF86AudioPlay spawn playerctl play-pause -p sayonara,%any
hc keybind XF86AudioNext spawn playerctl next -p sayonara,%any
###---  Backup Audio Controls   ---###
hc keybind $MOD-End spawn ~/.config/herbstluftwm/scripts/rofi_getsink.sh
hc keybind $MOD-Up spawn pactl set-sink-volume "$SETSINK" +5% # Raise Volume
hc keybind $MOD-Down spawn pactl set-sink-volume "$SETSINK" -5% # Lower Volume

###------------------------------------###
###---   Close/Remove/Quit/Reload   ---###
###------------------------------------###
# close window or remove frame
hc keybind $MOD-q close_or_remove
# quit herbstluftwm
hc keybind $MOD-Control-Shift-q quit
# live reload herbstluftwm configs
hc keybind $MOD-Shift-r reload

###----------------###
###---   TAGS   ---###
###----------------###
hc attr settings.default_frame_layout vertical

TAGNAMES=( {1..10} )
TAGKEYS=( "1" "2" "3" "4" "5" "6" "7" "8" "9" "0" )

hc rename default "${TAGNAMES[0]}" || true
for i in "${!TAGNAMES[@]}" ; do
	hc add "${TAGNAMES[$i]}"
	KEY="${TAGKEYS[$i]}"
	if [ -n "$KEY" ] ; then
		hc keybind "$MOD-$KEY" chain , silent substitute M tags."$i".my_monitor focus_monitor M , use_index "$i"
#		hc keybind "$MOD-$KEY" use_index "$i"
		hc keybind "$MOD-Shift-$KEY" move_index "$i"
	fi
done

###---------------------------###
###---   Add scratchpads   ---###
###---------------------------###
hc add sysadmin
hc add audio
hc keybind $MOD-minus spawn ~/.config/herbstluftwm/scripts/scratchpad.sh audio
hc keybind $MOD-grave spawn ~/.config/herbstluftwm/scripts/scratchpad.sh sysadmin
hc keybind $MOD-equal spawn ~/.config/herbstluftwm/scripts/scratchpad.sh
hc keybind $MOD-Shift-minus move audio
hc keybind $MOD-Shift-grave move sysadmin
hc keybind $MOD-Shift-equal move scratchpad

###--------------------###
###---   Tag Lock   ---###
###---              ---###
###---    Unused    ---###
###--------------------###
#hc keybind $MOD-t chain \
#	, new_attr string tags.focus.my_monitor \
#	, substitute M monitors.focus.index set_attr tags.focus.my_monitor M \
#	, try and \
#		. compare monitors.focus.name != "" \
#		. substitute M monitors.focus.name \
#				set_attr tags.focus.my_monitor M
#
#hc keybind $MOD-Shift-t \
#	remove_attr tags.focus.my_monitor

###---------------###
###---   EOF   ---###
###---------------###
