#!/usr/bin/env bash
# General alias...
alias pacs="pacman -Ss" \
	kiff="kitty +kitten diff" \
	mkdir="mkdir -v" \
	ls="ls --color=always --group-directories-first" \
	grep="grep --color=auto" \
	cfg="/usr/bin/git --git-dir=/home/zonric/.dotfiles/ --work-tree=$HOME" \
	cdiff="cfg diff" \
	pacman="pacman --color=auto" \
	vim="nvim" \
	vimcon="vim ~/.config/nvim/" \
	:q="exit" \

