#!/usr/bin/env bash
# General alias...
alias pacs="pacman -Ss" \
  kiff="kitty +kitten diff" \
  mkdir="mkdir -v" \
  ls="ls --color=auto --group-directories-first" \
  la="ls -A" \
  ll="ls -lh" \
  lla="ls -lAh" \
  grep="grep --color=auto" \
  icat="kitty icat" \
  cfg="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME" \
  cdiff="cfg diff" \
  pacman="pacman --color=auto" \
  vim="nvim" \
  :q="exit" \
  rm="trash" \
  rmdir="trash" \
  trash-ls="trash-list" \
