#!/usr/bin/env bash
# shellcheck disable=SC2034

WHITE=#FFFFFF
BLACK=#090618
GRAY=#222222

FOREGROUND=#DCD7BA
FOREGROUND_ALT=#1F1F28

BORDER=#7E9CD8
BORDER_ALT=#727169

NORMAL=#191726
NORMAL_ALT=#727169

ACTIVE=#7E9CD8
ACTIVE_ALT=#BF88AD

URGENT=#938AA9
URGENT_ALT=#C34043

ERROR=#E82424

# -- Kanagawa colors
#color_01: #090618    # Black (Host)
#color_02: #C34043    # Red (Syntax string)
#color_03: #76946A    # Green (Command)
#color_04: #C0A36E    # Yellow (Command second)
#color_05: #7E9CD8    # Blue (Path)
#color_06: #957FB8    # Magenta (Syntax var)
#color_07: #6A9589    # Cyan (Prompt)
#color_08: #DCD7BA    # White
#color_09: #727169    # Bright Black
#color_10: #E82424    # Bright Red (Command error)
#color_11: #98BB6C    # Bright Green (Exec)
#color_12: #E6C384    # Bright Yellow
#color_13: #7FB4CA    # Bright Blue (Folder)
#color_14: #938AA9    # Bright Magenta
#color_15: #7AA89F    # Bright Cyan
#color_16: #C8C093    # Bright White

#background: #1F1F28  # Background
#foreground: #DCD7BA  # Foreground (Text)

