#!/usr/bin/env sh

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set mouse_recenter_gap 0
hc set focus_crosses_monitor_boundaries false
hc set swap_monitors_to_get_tag false
hc set smart_frame_surroundings true
hc set smart_window_surroundings false

hc set frame_gap 2
hc set frame_padding 1
hc set show_frame_decorations if_empty
hc set frame_bg_transparent false
hc set frame_normal_opacity 65
hc set frame_active_opacity 85
hc set frame_bg_normal_color '#222'
hc set frame_bg_active_color '#000'
hc set frame_border_width 2
hc set frame_border_normal_color '#AAFFFF'
hc set frame_border_active_color '#AA55AA'

hc set window_gap 10

hc attr theme.border_width 3
hc attr theme.tight_decoration false
hc attr theme.title_when never

hc attr theme.normal.color '#669999'
hc attr theme.normal.border_width 3

hc attr theme.active.color '#66FF66'
hc attr theme.active.border_width 3

hc attr theme.floating.border_width 6
hc attr theme.floating.inner_color orange
hc attr theme.floating.inner_width 3

hc attr theme.urgent.border_width 6
hc attr theme.urgent.inner_color '#FF00FF'
hc attr theme.urgent.inner_width 3
hc attr theme.urgent.outer_color '#FF0000'
hc attr theme.urgent.outer_width 3
